// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace HotelProjekat.Migrations
{
    [DbContext(typeof(HotelContext))]
    [Migration("20220321032358_v1")]
    partial class v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.Korisnik", b =>
                {
                    b.Property<int>("IDKorisnika")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrTelefona")
                        .HasColumnType("int");

                    b.Property<int>("BrojPasosa")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IDKorisnika");

                    b.ToTable("Korisnik");
                });

            modelBuilder.Entity("Models.Prijava", b =>
                {
                    b.Property<int>("IDPrijave")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrojSobe")
                        .HasColumnType("int");

                    b.Property<int?>("KorisnikIDKorisnika")
                        .HasColumnType("int");

                    b.Property<int?>("ZaposleniIDRadnika")
                        .HasColumnType("int");

                    b.Property<int?>("ZgradaIDZgrade")
                        .HasColumnType("int");

                    b.HasKey("IDPrijave");

                    b.HasIndex("KorisnikIDKorisnika");

                    b.HasIndex("ZaposleniIDRadnika");

                    b.HasIndex("ZgradaIDZgrade");

                    b.ToTable("Prijava");
                });

            modelBuilder.Entity("Models.Zaposleni", b =>
                {
                    b.Property<int>("IDRadnika")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrTelefona")
                        .HasColumnType("int");

                    b.Property<int>("BrojLicence")
                        .HasColumnType("int");

                    b.Property<string>("ImeZaposleni")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Plata")
                        .HasColumnType("int");

                    b.Property<string>("PrezimeZaposleni")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IDRadnika");

                    b.ToTable("Zaposleni");
                });

            modelBuilder.Entity("Models.Zgrada", b =>
                {
                    b.Property<int>("IDZgrade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Grad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImeZgrade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDZgrade");

                    b.ToTable("Zgrada");
                });

            modelBuilder.Entity("Models.Prijava", b =>
                {
                    b.HasOne("Models.Korisnik", "Korisnik")
                        .WithMany("KorisnikPrijava")
                        .HasForeignKey("KorisnikIDKorisnika");

                    b.HasOne("Models.Zaposleni", "Zaposleni")
                        .WithMany("ZaposleniPrijava")
                        .HasForeignKey("ZaposleniIDRadnika");

                    b.HasOne("Models.Zgrada", "Zgrada")
                        .WithMany("ZgradaPrijava")
                        .HasForeignKey("ZgradaIDZgrade");

                    b.Navigation("Korisnik");

                    b.Navigation("Zaposleni");

                    b.Navigation("Zgrada");
                });

            modelBuilder.Entity("Models.Korisnik", b =>
                {
                    b.Navigation("KorisnikPrijava");
                });

            modelBuilder.Entity("Models.Zaposleni", b =>
                {
                    b.Navigation("ZaposleniPrijava");
                });

            modelBuilder.Entity("Models.Zgrada", b =>
                {
                    b.Navigation("ZgradaPrijava");
                });
#pragma warning restore 612, 618
        }
    }
}
